//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domolan.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Акции
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Акции()
        {
            this.Договоры = new HashSet<Договоры>();
        }
    
        public int КодАкции { get; set; }
        public string Акции1 { get; set; }
        public string Скорость_интернета { get; set; }
        public string Wi_Fi_маршрутизатор { get; set; }
        public string Антивирус_Dr_Web { get; set; }
        public string Цифровое_ТВ { get; set; }
        public string Облачный_Видеомониторниг { get; set; }
        public string Развлекательные_ресурсы { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договоры> Договоры { get; set; }
    }
}
