//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domolan.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договоры
    {
        public int КодДоговора { get; set; }
        public int КодАкции { get; set; }
        public int КодОборудования { get; set; }
        public int КодСвязи { get; set; }
        public int КодСотрудники { get; set; }
        public int КодТарифы { get; set; }
        public int Номер_Договора { get; set; }
        public System.DateTime Дата_договора { get; set; }
    
        public virtual Акции Акции { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Связи Связи { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Тарифы Тарифы { get; set; }
    }
}
